package: plus_bs5
version: '0.10.0-dev-2024-12-28'
author: Alexander Walther
supportpage: https://www.alexplus.de

requires:
    php:
        version: "^8.2"
    redaxo: ^5.17
    packages:
        mform: "^8"
        mediapool: "^2"
        media_manager: "^2"
        media_manager_responsive: ">=1,<3"
        yrewrite_metainfo: "^2"
        wenns_sein_muss: "^5"

page:
    title: translate:plus_bs5
    perm: plus_bs5

pages:
    plus_bs5/settings:
        title: translate:plus_bs5_settings
        perm: plus_bs5
    plus_bs5/settings/intro:
        title: translate:plus_bs5_settings_intro
        perm: plus_bs5
    plus_bs5/settings/template:
        title: translate:plus_bs5_settings_template
        perm: plus_bs5
    plus_bs5/settings/header:
        title: translate:plus_bs5_settings_header
        perm: plus_bs5
    plus_bs5/settings/module:
        title: translate:plus_bs5_settings_module
        perm: plus_bs5
    plus_bs5/settings/footer:
        title: translate:plus_bs5_settings_footer
        perm: plus_bs5
    plus_bs5/settings/emails:
        title: translate:plus_bs5_settings_emails
        perm: plus_bs5
    plus_bs5/settings/legal:
        title: translate:plus_bs5_settings_legal
        perm: plus_bs5
    plus_bs5/settings/dev:
        title: translate:plus_bs5_settings_dev
        perm: plus_bs5

config:
    vendor: "cdn"
    editor: "redactor-editor--text"
    nav_depth: 1
    mobile_nav_layout: modal
    text_more: "Mehr..."
    text_a18y_content: "Zum Inhalt springen..."
    text_slideshow_prev: Zurück
    text_slideshow_next: Weiter
    text_header_mobile_nav: Menü
    text_header_mobile_nav_title: Menü
    text_header_mobile_nav_close: Schließen
    dev: 0 # Aktivieren, um Module und Templates ins Addon zu schreiben
    search_it_article_id: 0 # Artikel-ID für die Suchergebnisse

# Verfügbare Module und Frontend-Übersetzung
module:
    bs5.accordion: "Akkordeon"
    bs5.alert: "Hinweis"
    bs5.divider: "Trennelement"
    bs5.downloads: "Downloads"
    bs5.events: "Termine"
    bs5.gallery: "Galerie"
    bs5.google_maps: "Google Maps"
    bs5.neues: "News"
    bs5.qanda: "Q&A"
    bs5.search_it: "Suche"
    bs5.staff: "Ansprechpersonen"
    bs5.structure.child_article: "Kategorien"
    bs5.structure.child_category: "Artikel"
    bs5.tabs: "Tabs"
    bs5.text: "<i class=\"bi bi-text\"></i> Text"
    bs5.video.mediapool: "Video (Mediapool)"
    bs5.video.youtube: "Video (YouTube)"
    bs5.search_it.result: "Suchergebnisse"
    school.contact: "Kollegium"
    school.contact.website_team: "Kategorien"
    school.hierachy: "Artikel"
    school.home.slides: "Startseite Slides"
    school.room: "Räume"
    school.teacher: "Kollegium"
    school.team.contact: "Kontakt"
    school.team.person: "Ansprechperson"
    school.workgroup: "AGs"
    school.workgroup.page: "AGs Detailseite"
