package: plus_bs5
version: '0.0.4'
author: Alexander Walther
supportpage: https://www.alexplus.de

requires:
    php:
        version: ">7.3"
    redaxo: ^5.12
    packages:
        mediapool: ">=2"
        media_manager: ">=2"
        yrewrite_metainfo: "^1"

page:
    title: Bootstrap 5
    perm: admin

pages:
    plus_bs5/settings:
        title: translate:Einstellungen
        perm: admin

config:
    vendor: "cdn"
