package: plus_bs5
version: '0.0.4'
author: Alexander Walther
supportpage: https://www.alexplus.de

requires:
    php:
        version: ">7.3"
    redaxo: ^5.12
    packages:
        mediapool: ">=2"
        media_manager: ">=2"
        yrewrite_metainfo: "^1"

page:
    title: Bootstrap 5
    perm: plus_bs5

pages:
    plus_bs5/settings:
        title: translate:plus_bs5_settings
        perm: plus_bs5
    plus_bs5/settings/intro:
        title: translate:plus_bs5_settings_intro
        perm: plus_bs5
    plus_bs5/settings/header:
        title: translate:plus_bs5_settings_header
        perm: plus_bs5
    plus_bs5/settings/module:
        title: translate:plus_bs5_settings_module
        perm: plus_bs5
    plus_bs5/settings/footer:
        title: translate:plus_bs5_settings_footer
        perm: plus_bs5
    plus_bs5/settings/emails:
        title: translate:plus_bs5_settings_emails
        perm: plus_bs5
    plus_bs5/settings/legal:
        title: translate:plus_bs5_settings_legal
        perm: plus_bs5

config:
    vendor: "cdn"
    editor: "redactor-editor--text"
    container_class: "p-3 shadow bg-white"
    nav_depth: 1
    dev: 0 # Aktivieren, um Module und Templates ins Addon zu schreiben
