package: plus_bs5
version: '0.2.0-dev-2024-12-12'
author: Alexander Walther
supportpage: https://www.alexplus.de

requires:
    php:
        version: "^8.0"
    redaxo: ^5.17
    packages:
        mform: "^8"
        mediapool: "^2"
        media_manager: "^2"
        yrewrite_metainfo: "^2"
        wenns_sein_muss: "^5"

page:
    title: translate:plus_bs5
    perm: plus_bs5

pages:
    plus_bs5/settings:
        title: translate:plus_bs5_settings
        perm: plus_bs5
    plus_bs5/settings/intro:
        title: translate:plus_bs5_settings_intro
        perm: plus_bs5
    plus_bs5/settings/template:
        title: translate:plus_bs5_settings_template
        perm: plus_bs5
    plus_bs5/settings/header:
        title: translate:plus_bs5_settings_header
        perm: plus_bs5
    plus_bs5/settings/module:
        title: translate:plus_bs5_settings_module
        perm: plus_bs5
    plus_bs5/settings/footer:
        title: translate:plus_bs5_settings_footer
        perm: plus_bs5
    plus_bs5/settings/emails:
        title: translate:plus_bs5_settings_emails
        perm: plus_bs5
    plus_bs5/settings/legal:
        title: translate:plus_bs5_settings_legal
        perm: plus_bs5

config:
    vendor: "cdn"
    editor: "redactor-editor--text"
    container_class: "p-3 shadow bg-white"
    nav_depth: 1
    text_more: "Mehr..."
    text_a18y_content: "Zum Inhalt springen..."
    text_slideshow_prev: Zurück
    text_slideshow_next: Weiter
    text_header_mobile_nav: Menü
    text_header_mobile_nav_title: Menü
    text_header_mobile_nav_close: Schließen
    dev: 0 # Aktivieren, um Module und Templates ins Addon zu schreiben
    mobile_nav_layout: modal
    search_it_article_id: 0 # Artikel-ID für die Suchergebnisse
