package: plus_bs5
version: '0.1.4'
author: Alexander Walther
supportpage: https://www.alexplus.de

requires:
    php:
        version: ">7.3"
    redaxo: ^5.14
    packages:
        mform: "^7.3"
        mediapool: "^2"
        media_manager: "^2"
        yrewrite_metainfo: "^1"
        wenns_sein_muss: "^4"

page:
    title: translate:plus_bs5
    perm: plus_bs5

pages:
    plus_bs5/settings:
        title: translate:plus_bs5_settings
        perm: plus_bs5
    plus_bs5/settings/intro:
        title: translate:plus_bs5_settings_intro
        perm: plus_bs5
    plus_bs5/settings/template:
        title: translate:plus_bs5_settings_template
        perm: plus_bs5
    plus_bs5/settings/header:
        title: translate:plus_bs5_settings_header
        perm: plus_bs5
    plus_bs5/settings/module:
        title: translate:plus_bs5_settings_module
        perm: plus_bs5
    plus_bs5/settings/footer:
        title: translate:plus_bs5_settings_footer
        perm: plus_bs5
    plus_bs5/settings/emails:
        title: translate:plus_bs5_settings_emails
        perm: plus_bs5
    plus_bs5/settings/legal:
        title: translate:plus_bs5_settings_legal
        perm: plus_bs5

config:
    vendor: "cdn"
    editor: "redactor-editor--text"
    container_class: "p-3 shadow bg-white"
    nav_depth: 1
    text_more: "Mehr..."
    text_a18y_content: "Zum Inhalt springen..."
    text_slideshow_prev: Zurück
    text_slideshow_next: Weiter
    dev: 0 # Aktivieren, um Module und Templates ins Addon zu schreiben
